// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdmg3gi8h9jKA_fsxXmrltg0aJUFJqf6M',
    appId: '1:323401473101:web:a78c76412c8a8c123ad004',
    messagingSenderId: '323401473101',
    projectId: 'aurify-pushnotification',
    authDomain: 'aurify-pushnotification.firebaseapp.com',
    storageBucket: 'aurify-pushnotification.firebasestorage.app',
    measurementId: 'G-LDPBNK46Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCevQoxXL99yB4k1b48S_Ivjv48c88m1l0',
    appId: '1:323401473101:android:7f333db0fd6eff813ad004',
    messagingSenderId: '323401473101',
    projectId: 'aurify-pushnotification',
    storageBucket: 'aurify-pushnotification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5rbOEIk7FA2qBfFRMH5Ewrjr17U5wOw',
    appId: '1:323401473101:ios:f9014f54ac16c8af3ad004',
    messagingSenderId: '323401473101',
    projectId: 'aurify-pushnotification',
    storageBucket: 'aurify-pushnotification.firebasestorage.app',
    iosBundleId: 'com.tecnavis.swissgold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS5rbOEIk7FA2qBfFRMH5Ewrjr17U5wOw',
    appId: '1:323401473101:ios:f9014f54ac16c8af3ad004',
    messagingSenderId: '323401473101',
    projectId: 'aurify-pushnotification',
    storageBucket: 'aurify-pushnotification.firebasestorage.app',
    iosBundleId: 'com.tecnavis.swissgold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdmg3gi8h9jKA_fsxXmrltg0aJUFJqf6M',
    appId: '1:323401473101:web:2389a22e4a88e3893ad004',
    messagingSenderId: '323401473101',
    projectId: 'aurify-pushnotification',
    authDomain: 'aurify-pushnotification.firebaseapp.com',
    storageBucket: 'aurify-pushnotification.firebasestorage.app',
    measurementId: 'G-88VPEJF9HY',
  );

}